### ISSUE TITLE
Can't install on CentOS 7

### ISSUE THREAD

**Issue by pseudopirate** [noobient/killinuxfloor#45]
Hey, man!

I'm just trying to install this wonderful server, following [this](https://noobient.com/2019/01/11/killinuxfloor-killing-floor-2-server-on-linux/) guide and I have troubles at installation step. It says that my CentOS version is too old, but I've updated it just right before running the installation.
Here some copypaste of my terminal
```bash
$ sudo ./install.sh
This will install killinuxfloor on this machine. Press y to continue: y
Checking CentOS version... error! Your CentOS is too old.
Update with yum update, then reboot.

$ rpm -qa centos-release
centos-release-7-7.1908.0.el7.centos.x86_64
```

Could you provide me with some help on this issue?
Thanks a lot!

**Comment by bviktor** [comment]
Hey! What does `yum update` do?

**Comment by pseudopirate** [comment]
> Hey! What does `yum update` do?

```bash
$ sudo yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.datahouse.ru
 * extras: mirror.tversu.ru
 * updates: mirrors.datahouse.ru
No packages marked for update
```

**Comment by bviktor** [comment]
Mhm. What does `cat /etc/centos-release` say?

**Comment by pseudopirate** [comment]
`CentOS Linux release 7.7.1908 (Core)`

**Comment by bviktor** [comment]
Ah okay I forgot there's been no release for a while. Please use the git version.

```
yum install git
git clone https://github.com/noobient/killinuxfloor.git
```

Then try again.

**Comment by pseudopirate** [comment]
> Ah okay I forgot there's been no release for a while. Please use the git version.
> 
> ```
> yum install git
> git clone https://github.com/noobient/killinuxfloor.git
> ```
> 
> Then try again.
Thanks, it helped

**Comment by bviktor** [comment]
Awesome, glad to hear that :)
