### ISSUE TITLE
Changing disk 

### ISSUE THREAD

**Issue by assil4** [noobient/killinuxfloor#47]
i'm using centos 8
What did do:
1.I installed kf2-centos(from Dedicated Killing Floor 2 Server on Linux v2 link)
2. i changed user disk by using "usermod -m -d otherdisk steam" (since i don't have enough space)
and than i've got an error when i tried to start my server with cmd "killinuxfloor start" which is:
**Warning: The unit file, source configuration file or drop-ins of kf2.service changed on disk. Run 'sys>
● kf2.service - KF2 Server
   Loaded: loaded (/etc/systemd/system/kf2.service; bad; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kf2.service.d
           └─kf2.service.conf
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-01-16 10:24:44 UTC; 2s ago
  Process: 10979 ExecStartPre=/usr/bin/truncate --size=0 /datadrive/steam/Steam/logs/kf2.txt (code=exi>
 Main PID: 8721 (code=killed, signal=TERM)

Jan 16 10:24:44 VPS systemd[1]: kf2.service: Control process exited, code=exited status=209
Jan 16 10:24:44 VPS systemd[1]: kf2.service: Failed with result 'exit-code'.
Jan 16 10:24:44 VPS systemd[1]: Failed to start KF2 Server.**
i've tried to edit  kf2.service

**Comment by bviktor** [comment]
Well tbh I'm not sure what and how you did. kf2-centos is pretty old, it's been killinuxfloor for like... years.

In any case, everything relies on the `/home/steam` path. You can move its content to a different disk, but make sure that there's a `/home/steam` symlink pointing to the new disk, and also that the `steam` user has read-write permissions to the new place.

**Comment by bviktor** [comment]
The "Dedicated Killing Floor 2 Server on Linux v2" is listed in the Deprecated section with a warning that "You should not use these", and the article also begins with "This tutorial is deprecated. Please use the revised guide. This one is only here for historical reference." so I don't understand why you'd use that. Use the new guide please.

**Comment by assil4** [comment]
Thanks
