### ISSUE TITLE
Workshop Items Not Downloading

### ISSUE THREAD

**Issue by Jernee** [noobient/killinuxfloor#63]
Followed directions exactly and workshops items won't download. Just show state of 0 then 8.

**Comment by Jernee** [comment]
> Yeah, TWI broke it AGAIN with the latest KF2 patch. I'm still trying to find a workaround, but the previous one causes a segfault, so it'll most likely require action on their part.
> 
> https://noobient.com/2019/05/12/fixing-killing-floor-2-linux-server-workshop-downloads/
> 
> TLDR they link to (and ship) wrong versions of `steamclient.so` which they shouldn't do at all in the first place, because Steam ships its own, but for whatever reason TWI sometimes randomly decides to ship their on version. Or 3 different versions of it. Don't ask me why, it's beyond comprehension.
> 
> In the meanwhile you can try nagging them about it... the errors messages can be found in `Steam/logs/workshop_logs.txt` or something like that, it clearly shows those issues about no connection to servers etc.

Ya I was reading about that and saw that you'd made the workaround. Was hoping it was just something I was doing wrong and not them creating the problem again. Thanks for the answer though.

**Comment by bviktor** [comment]
Hey, I pushed a commit that may solve the issue. Could you please do

```
git pull
./install.sh -e "skip_kfgame=True"
```

in the killinuxfloor directory, then retry the workshop downloads?

**Comment by Jernee** [comment]
> Hey, I pushed a commit that may solve the issue. Could you please do
> 
> ```
> git pull
> ./install.sh -e "skip_kfgame=True"
> ```
> 
> in the killinuxfloor directory, then retry the workshop downloads?

Looks like it worked. You're awesome, thanks.

**Comment by bviktor** [comment]
Awesome :) Closing the issue then.

For reference, the relevant commit is 161d2ee3af05e006ef004a59d507379186991ef1
