### ISSUE TITLE
There must be a blank line to parse the whole My-Maps.csv

### ISSUE THREAD

**Issue by triuk** [noobient/killinuxfloor#68]
Hi, as the title say, there must be a blank line after the last item to parse the whole file. If there is not, the last workshop item is not downloaded. Maybe it affects the other files too. It is not a crucial problem, but it should be noted at least :)

**Comment by bviktor** [comment]
Committed some fixes, please try now :)

**Comment by bviktor** [comment]
Hmm... I think this will only fix the EOLs *after* it applies the config, lemme check...

**Comment by bviktor** [comment]
Yup.... let me fix this... again :D

**Comment by bviktor** [comment]
Alright, this should actually work now, please check :)

**Comment by triuk** [comment]
```
sudo -iu steam
cd killinuxfloor
git pull
```
I added map, it works. Thanks.

**Comment by bviktor** [comment]
Awesome, thanks a lot for your reports :))
