### ISSUE TITLE
Crash when no custom maps

### ISSUE THREAD

**Issue by k0dat** [noobient/killinuxfloor#80]
When I comment out the two default custom maps in My-Maps.csv and run klf apply, I get the following 'unbound variable' error. If uncomment one then kf apply will work. Not the end of the world since I'm just going to add my own selection of custom maps, but thought I'd point it out since there might be some admins that just want to have a server with official maps only.

```
Adding map cycle for all workshop maps... done.
Adding map cycle for all stock maps... done.
/home/steam/bin/klf: line 358: MAPS_WORKSHOP: unbound variable
```

**Comment by bviktor** [comment]
Oops, you're right, the array is initialized for mutators, but not for maps for whatever reason :D
