### ISSUE TITLE
Install fails on Fedora Server 37 with namespace issue.

### ISSUE THREAD

**Issue by Bonktacular** [noobient/killinuxfloor#84]
Installer fails at bviktor.servicecheck with the message of 'Please change namespace from "bviktor" to "noobient".
Currently workaround is to find and replace all occurrences of 'bviktor' with 'noobient' in the project.

**Comment by bviktor** [comment]
Yeah, there were some namespace changes. I pushed some fixes to Git, can you please try again?

**Comment by bviktor** [comment]
Please note, however, that F37 will be EOL'd in 2 days, so you're strongly advised to upgrade to 38 or 39.

**Comment by Bonktacular** [comment]
Noted, and your changes do solve the problem. I'm not sure if the new error during the Initialize KF2 config step is specific to me, but you can consider this issue closed. Thank you!
