### ISSUE TITLE
Is the installer still working ? Not for me

### ISSUE THREAD

**Issue by TomMedn** [noobient/killinuxfloor#85]
Hello, is this installer still working ?
When running install.sh I get a error, see below
BTW i don't care about rsyslog so If there is a way to ignore it im good
Maybe I should made a post in discussion rather than here ? anyway, thanks for help

TASK [install : Install rsyslog] **************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [install : Install log rotation for system logs] *****************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failures": ["rsyslog-logrotate Aucune correspondance pour le paramètre: rsyslog-logrotate"], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

PLAY RECAP ************************************************************************************************************************************************************************
127.0.0.1                  : ok=50   changed=1    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0

**Comment by bviktor** [comment]
What OS is this on?

**Comment by TomMedn** [comment]
Hello,
The issue is occuring on fresh install of Fedora 35 and Fedora 39. 
Thanks

**Comment by bviktor** [comment]
Interesting. In any case, both of those are EOL. Now I pushed a bunch of fixes, although they're not related to the issue you're having.

Can you please test on Fedora 40/41 or AlmaLinux 8/9? Those I just tested, and they seem to work fine.

**Comment by TomMedn** [comment]
Hello, 
I will test tonight and give you some feedback asap.
Thank you!

**Comment by bviktor** [comment]
Thanks in advance!

**Comment by TomMedn** [comment]
Hello again,
I encountered no issues after switching to Fedora 41 OS.
Thank you for your assistance.
May I suggest updating your tutorial for clarity, (it mention fedora 35 so I tought it was mandatory).
I truly appreciate the effort put into this community project, more user-friendly than some professional solutions I've used.
I'll now enjoy my new server,
Regards

**Comment by TomMedn** [comment]
Using a more recent, supported OS fixed the issue.

**Comment by bviktor** [comment]
Ah, thanks a lot for the feedback, and also for the kind words :) Your concern about the docs is absolutely legit, updated it just now.

Happy playing!
